/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from "../../common";

export interface MerkleTreeExposedInterface extends utils.Interface {
  functions: {
    "appendMessage(bytes)": FunctionFragment;
    "getMerkleRoot()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "appendMessage" | "getMerkleRoot"): FunctionFragment;

  encodeFunctionData(functionFragment: "appendMessage", values: [PromiseOrValue<BytesLike>]): string;
  encodeFunctionData(functionFragment: "getMerkleRoot", values?: undefined): string;

  decodeFunctionResult(functionFragment: "appendMessage", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMerkleRoot", data: BytesLike): Result;

  events: {};
}

export interface MerkleTreeExposed extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MerkleTreeExposedInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    appendMessage(
      _leaf: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getMerkleRoot(overrides?: CallOverrides): Promise<[string]>;
  };

  appendMessage(
    _leaf: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getMerkleRoot(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    appendMessage(_leaf: PromiseOrValue<BytesLike>, overrides?: CallOverrides): Promise<void>;

    getMerkleRoot(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    appendMessage(
      _leaf: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getMerkleRoot(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    appendMessage(
      _leaf: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getMerkleRoot(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
