/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from "../common";

export interface VeaInboxTouchInterface extends utils.Interface {
  functions: {
    "touch(uint256)": FunctionFragment;
    "veaInbox()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "touch" | "veaInbox"): FunctionFragment;

  encodeFunctionData(functionFragment: "touch", values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(functionFragment: "veaInbox", values?: undefined): string;

  decodeFunctionResult(functionFragment: "touch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "veaInbox", data: BytesLike): Result;

  events: {};
}

export interface VeaInboxTouch extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: VeaInboxTouchInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    touch(
      random: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    veaInbox(overrides?: CallOverrides): Promise<[string]>;
  };

  touch(
    random: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  veaInbox(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    touch(random: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<void>;

    veaInbox(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    touch(
      random: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    veaInbox(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    touch(
      random: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    veaInbox(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
