# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: veashi-envio-yaho
contracts:
  - name: Yaho
    abi_file_path: ./abis/Yaho.json
    handler: src/EventHandlers.ts
    events:
      - event: MessageDispatched
        field_selection:
          transaction_fields:
            - hash
chains:
  - id: 1514
    start_block: 12699901
    rpc:
      url: https://mainnet.storyrpc.io
    contracts:
      - name: Yaho
        address:
          - 0x0313f25f51f8846fdDFaBCb7F0672e4D3E1C0E76
  - id: 42161
    start_block: 427763138
    contracts:
      - name: Yaho
        address:
          - 0xD0375320591ff87797CEb03CBeE80C82fD61BC77
  - id: 421614
    start_block: 92669889
    contracts:
      - name: Yaho
        address:
          - 0xDbdF80c87f414fac8342e04D870764197bD3bAC7
