FROM node:18-alpine

RUN yarn policies set-version 4.2.2

USER node

WORKDIR /home/node

COPY --chown=node:node package.json yarn.lock .yarnrc.yml ./
RUN yarn install

COPY --chown=node:node relayer-cli/package.json ./relayer-cli/
COPY --chown=node:node contracts/package.json ./contracts/

RUN yarn --cwd ./relayer-cli/ install

COPY --chown=node:node ./relayer-cli/ ./relayer-cli/

CMD ["yarn", "workspace", "relayer-cli", "start-testnet-relayer"]


