type Claim @entity {
  id: ID!
  outbox: Outbox! # address
  epoch: BigInt! # uint64
  stateroot: Bytes! # bytes32
  bridger: Bytes! # address
  timestamp: BigInt!
  challenged: Boolean!
  challenge: Challenge @derivedFrom(field: "claim")
  verification: Verification @derivedFrom(field: "claim")
  verified: Boolean!
  honest: Boolean!
  txHash: Bytes!
}

type Outbox @entity(immutable: true) {
  id: Bytes! # address
  claims: [Claim!]! @derivedFrom(field: "outbox")
}

type Challenge @entity {
  id: ID!
  claim: Claim!
  txHash: Bytes!
  timestamp: BigInt!
  challenger: Bytes! # address
  honest: Boolean!
}

type Verification @entity {
  id: ID!
  claim: Claim!
  timestamp: BigInt!
  caller: Bytes! # address
  txHash: Bytes!
}

type Message @entity {
  id: ID!
  outbox: Outbox! # address
  timestamp: BigInt!
  txHash: Bytes!
  relayer: Bytes! # address
  proof: Bytes!
}

type Ref @entity {
  id: ID!
  outbox: Outbox! # address
  totalClaims: BigInt!
  totalMessages: BigInt!
  totalChallenges: BigInt!
}
