/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from "../../common";

export type ClaimStruct = {
  stateRoot: PromiseOrValue<BytesLike>;
  claimer: PromiseOrValue<string>;
  timestampClaimed: PromiseOrValue<BigNumberish>;
  timestampVerification: PromiseOrValue<BigNumberish>;
  blocknumberVerification: PromiseOrValue<BigNumberish>;
  honest: PromiseOrValue<BigNumberish>;
  challenger: PromiseOrValue<string>;
};

export type ClaimStructOutput = [string, string, number, number, number, number, string] & {
  stateRoot: string;
  claimer: string;
  timestampClaimed: number;
  timestampVerification: number;
  blocknumberVerification: number;
  honest: number;
  challenger: string;
};

export interface IVeaOutboxOnL1Interface extends utils.Interface {
  functions: {
    "resolveDisputedClaim(uint256,bytes32,(bytes32,address,uint32,uint32,uint32,uint8,address))": FunctionFragment;
    "sendMessage(bytes32[],uint64,address,bytes)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "resolveDisputedClaim" | "sendMessage"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "resolveDisputedClaim",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BytesLike>, ClaimStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "sendMessage",
    values: [
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "resolveDisputedClaim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sendMessage", data: BytesLike): Result;

  events: {};
}

export interface IVeaOutboxOnL1 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IVeaOutboxOnL1Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    resolveDisputedClaim(
      _epoch: PromiseOrValue<BigNumberish>,
      _stateRoot: PromiseOrValue<BytesLike>,
      _claim: ClaimStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sendMessage(
      _proof: PromiseOrValue<BytesLike>[],
      _msgId: PromiseOrValue<BigNumberish>,
      _to: PromiseOrValue<string>,
      _message: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  resolveDisputedClaim(
    _epoch: PromiseOrValue<BigNumberish>,
    _stateRoot: PromiseOrValue<BytesLike>,
    _claim: ClaimStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sendMessage(
    _proof: PromiseOrValue<BytesLike>[],
    _msgId: PromiseOrValue<BigNumberish>,
    _to: PromiseOrValue<string>,
    _message: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    resolveDisputedClaim(
      _epoch: PromiseOrValue<BigNumberish>,
      _stateRoot: PromiseOrValue<BytesLike>,
      _claim: ClaimStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    sendMessage(
      _proof: PromiseOrValue<BytesLike>[],
      _msgId: PromiseOrValue<BigNumberish>,
      _to: PromiseOrValue<string>,
      _message: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    resolveDisputedClaim(
      _epoch: PromiseOrValue<BigNumberish>,
      _stateRoot: PromiseOrValue<BytesLike>,
      _claim: ClaimStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sendMessage(
      _proof: PromiseOrValue<BytesLike>[],
      _msgId: PromiseOrValue<BigNumberish>,
      _to: PromiseOrValue<string>,
      _message: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    resolveDisputedClaim(
      _epoch: PromiseOrValue<BigNumberish>,
      _stateRoot: PromiseOrValue<BytesLike>,
      _claim: ClaimStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sendMessage(
      _proof: PromiseOrValue<BytesLike>[],
      _msgId: PromiseOrValue<BigNumberish>,
      _to: PromiseOrValue<string>,
      _message: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
