/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IArbSys, IArbSysInterface } from "../../../canonical/arbitrum/IArbSys";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "destination",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "sendTxToL1",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IArbSys__factory {
  static readonly abi = _abi;
  static createInterface(): IArbSysInterface {
    return new utils.Interface(_abi) as IArbSysInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IArbSys {
    return new Contract(address, _abi, signerOrProvider) as IArbSys;
  }
}
