/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { ISequencerInbox, ISequencerInboxInterface } from "../../../canonical/arbitrum/ISequencerInbox";

const _abi = [
  {
    inputs: [],
    name: "maxTimeVariation",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ISequencerInbox__factory {
  static readonly abi = _abi;
  static createInterface(): ISequencerInboxInterface {
    return new utils.Interface(_abi) as ISequencerInboxInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ISequencerInbox {
    return new Contract(address, _abi, signerOrProvider) as ISequencerInbox;
  }
}
