/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IReceiverGatewayMock__factory } from "./IReceiverGatewayMock__factory";
export { ReceiverGatewayMock__factory } from "./ReceiverGatewayMock__factory";
export { SenderGatewayMock__factory } from "./SenderGatewayMock__factory";
