/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumber, BytesLike, CallOverrides, PopulatedTransaction, Signer, utils } from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from "../../../common";

export interface OutboxMockInterface extends utils.Interface {
  functions: {
    "l2ToL1Sender()": FunctionFragment;
    "veaInbox()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "l2ToL1Sender" | "veaInbox"): FunctionFragment;

  encodeFunctionData(functionFragment: "l2ToL1Sender", values?: undefined): string;
  encodeFunctionData(functionFragment: "veaInbox", values?: undefined): string;

  decodeFunctionResult(functionFragment: "l2ToL1Sender", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "veaInbox", data: BytesLike): Result;

  events: {};
}

export interface OutboxMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: OutboxMockInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    l2ToL1Sender(overrides?: CallOverrides): Promise<[string]>;

    veaInbox(overrides?: CallOverrides): Promise<[string]>;
  };

  l2ToL1Sender(overrides?: CallOverrides): Promise<string>;

  veaInbox(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    l2ToL1Sender(overrides?: CallOverrides): Promise<string>;

    veaInbox(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    l2ToL1Sender(overrides?: CallOverrides): Promise<BigNumber>;

    veaInbox(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    l2ToL1Sender(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    veaInbox(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
