/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from "../../common";

export interface IReceiverGatewayMockInterface extends utils.Interface {
  functions: {
    "receiveMessage(address,uint256)": FunctionFragment;
    "senderGateway()": FunctionFragment;
    "veaOutbox()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "receiveMessage" | "senderGateway" | "veaOutbox"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "receiveMessage",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "senderGateway", values?: undefined): string;
  encodeFunctionData(functionFragment: "veaOutbox", values?: undefined): string;

  decodeFunctionResult(functionFragment: "receiveMessage", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "senderGateway", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "veaOutbox", data: BytesLike): Result;

  events: {};
}

export interface IReceiverGatewayMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IReceiverGatewayMockInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    receiveMessage(
      msgSender: PromiseOrValue<string>,
      _data: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    senderGateway(overrides?: CallOverrides): Promise<[string]>;

    veaOutbox(overrides?: CallOverrides): Promise<[string]>;
  };

  receiveMessage(
    msgSender: PromiseOrValue<string>,
    _data: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  senderGateway(overrides?: CallOverrides): Promise<string>;

  veaOutbox(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    receiveMessage(
      msgSender: PromiseOrValue<string>,
      _data: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    senderGateway(overrides?: CallOverrides): Promise<string>;

    veaOutbox(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    receiveMessage(
      msgSender: PromiseOrValue<string>,
      _data: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    senderGateway(overrides?: CallOverrides): Promise<BigNumber>;

    veaOutbox(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    receiveMessage(
      msgSender: PromiseOrValue<string>,
      _data: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    senderGateway(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    veaOutbox(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
