/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from "../../common";

export interface ReceiverGatewayMockInterface extends utils.Interface {
  functions: {
    "data()": FunctionFragment;
    "messageCount()": FunctionFragment;
    "receiveMessage(address)": FunctionFragment;
    "receiveMessage(address,uint256)": FunctionFragment;
    "senderGateway()": FunctionFragment;
    "veaOutbox()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "data"
      | "messageCount"
      | "receiveMessage(address)"
      | "receiveMessage(address,uint256)"
      | "senderGateway"
      | "veaOutbox"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "data", values?: undefined): string;
  encodeFunctionData(functionFragment: "messageCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "receiveMessage(address)", values: [PromiseOrValue<string>]): string;
  encodeFunctionData(
    functionFragment: "receiveMessage(address,uint256)",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "senderGateway", values?: undefined): string;
  encodeFunctionData(functionFragment: "veaOutbox", values?: undefined): string;

  decodeFunctionResult(functionFragment: "data", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "messageCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "receiveMessage(address)", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "receiveMessage(address,uint256)", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "senderGateway", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "veaOutbox", data: BytesLike): Result;

  events: {};
}

export interface ReceiverGatewayMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ReceiverGatewayMockInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    data(overrides?: CallOverrides): Promise<[BigNumber]>;

    messageCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    "receiveMessage(address)"(
      messageSender: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "receiveMessage(address,uint256)"(
      messageSender: PromiseOrValue<string>,
      _data: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    senderGateway(overrides?: CallOverrides): Promise<[string]>;

    veaOutbox(overrides?: CallOverrides): Promise<[string]>;
  };

  data(overrides?: CallOverrides): Promise<BigNumber>;

  messageCount(overrides?: CallOverrides): Promise<BigNumber>;

  "receiveMessage(address)"(
    messageSender: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "receiveMessage(address,uint256)"(
    messageSender: PromiseOrValue<string>,
    _data: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  senderGateway(overrides?: CallOverrides): Promise<string>;

  veaOutbox(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    data(overrides?: CallOverrides): Promise<BigNumber>;

    messageCount(overrides?: CallOverrides): Promise<BigNumber>;

    "receiveMessage(address)"(messageSender: PromiseOrValue<string>, overrides?: CallOverrides): Promise<void>;

    "receiveMessage(address,uint256)"(
      messageSender: PromiseOrValue<string>,
      _data: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    senderGateway(overrides?: CallOverrides): Promise<string>;

    veaOutbox(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    data(overrides?: CallOverrides): Promise<BigNumber>;

    messageCount(overrides?: CallOverrides): Promise<BigNumber>;

    "receiveMessage(address)"(
      messageSender: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "receiveMessage(address,uint256)"(
      messageSender: PromiseOrValue<string>,
      _data: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    senderGateway(overrides?: CallOverrides): Promise<BigNumber>;

    veaOutbox(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    data(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    messageCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "receiveMessage(address)"(
      messageSender: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "receiveMessage(address,uint256)"(
      messageSender: PromiseOrValue<string>,
      _data: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    senderGateway(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    veaOutbox(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
