/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumber, BytesLike, CallOverrides, PopulatedTransaction, Signer, utils } from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from "../../../common";

export interface VeaInboxSaveSnapshotInterface extends utils.Interface {
  functions: {
    "veaInbox()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "veaInbox"): FunctionFragment;

  encodeFunctionData(functionFragment: "veaInbox", values?: undefined): string;

  decodeFunctionResult(functionFragment: "veaInbox", data: BytesLike): Result;

  events: {};
}

export interface VeaInboxSaveSnapshot extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: VeaInboxSaveSnapshotInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    veaInbox(overrides?: CallOverrides): Promise<[string]>;
  };

  veaInbox(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    veaInbox(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    veaInbox(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    veaInbox(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
