[profile.default]
src = "src"
out = "out"
libs = ["lib","../node_modules/"]
fs_permissions = [
    { access = "read-write", path = "./broadcast" }
]

[lint]
severity = ['high', 'medium']
ignore = ['../**/*.sol']

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
