/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumber, BytesLike, CallOverrides, PopulatedTransaction, Signer, utils } from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from "../../common";

export interface ISequencerInboxInterface extends utils.Interface {
  functions: {
    "maxTimeVariation()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "maxTimeVariation"): FunctionFragment;

  encodeFunctionData(functionFragment: "maxTimeVariation", values?: undefined): string;

  decodeFunctionResult(functionFragment: "maxTimeVariation", data: BytesLike): Result;

  events: {};
}

export interface ISequencerInbox extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ISequencerInboxInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    maxTimeVariation(overrides?: CallOverrides): Promise<[BigNumber, BigNumber, BigNumber, BigNumber]>;
  };

  maxTimeVariation(overrides?: CallOverrides): Promise<[BigNumber, BigNumber, BigNumber, BigNumber]>;

  callStatic: {
    maxTimeVariation(overrides?: CallOverrides): Promise<[BigNumber, BigNumber, BigNumber, BigNumber]>;
  };

  filters: {};

  estimateGas: {
    maxTimeVariation(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    maxTimeVariation(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
