/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISequencerDelayUpdatable,
  ISequencerDelayUpdatableInterface,
} from "../../../interfaces/updaters/ISequencerDelayUpdatable";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_newSequencerDelayLimit",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_timestamp",
        type: "uint256",
      },
    ],
    name: "updateSequencerDelayLimit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISequencerDelayUpdatable__factory {
  static readonly abi = _abi;
  static createInterface(): ISequencerDelayUpdatableInterface {
    return new utils.Interface(_abi) as ISequencerDelayUpdatableInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ISequencerDelayUpdatable {
    return new Contract(address, _abi, signerOrProvider) as ISequencerDelayUpdatable;
  }
}
