/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from "../../common";

export type ClaimStruct = {
  stateRoot: PromiseOrValue<BytesLike>;
  claimer: PromiseOrValue<string>;
  timestampClaimed: PromiseOrValue<BigNumberish>;
  timestampVerification: PromiseOrValue<BigNumberish>;
  blocknumberVerification: PromiseOrValue<BigNumberish>;
  honest: PromiseOrValue<BigNumberish>;
  challenger: PromiseOrValue<string>;
};

export type ClaimStructOutput = [string, string, number, number, number, number, string] & {
  stateRoot: string;
  claimer: string;
  timestampClaimed: number;
  timestampVerification: number;
  blocknumberVerification: number;
  honest: number;
  challenger: string;
};

export interface VeaOutboxMockArbToEthInterface extends utils.Interface {
  functions: {
    "BURN_ADDRESS()": FunctionFragment;
    "arbSys()": FunctionFragment;
    "bridge()": FunctionFragment;
    "burn()": FunctionFragment;
    "censorshipTestStatus((bytes32,address,uint32,uint32,uint32,uint8,address))": FunctionFragment;
    "challenge(uint256,(bytes32,address,uint32,uint32,uint32,uint8,address))": FunctionFragment;
    "challenge(uint256,(bytes32,address,uint32,uint32,uint32,uint8,address),address)": FunctionFragment;
    "claim(uint256,bytes32)": FunctionFragment;
    "claimHashes(uint256)": FunctionFragment;
    "deposit()": FunctionFragment;
    "depositPlusReward()": FunctionFragment;
    "epochAt(uint256)": FunctionFragment;
    "epochNow()": FunctionFragment;
    "epochPeriod()": FunctionFragment;
    "executeSequencerDelayLimitDecreaseRequest()": FunctionFragment;
    "hashClaim((bytes32,address,uint32,uint32,uint32,uint8,address))": FunctionFragment;
    "isMsgRelayed(uint256)": FunctionFragment;
    "latestVerifiedEpoch()": FunctionFragment;
    "maxMissingBlocks()": FunctionFragment;
    "minChallengePeriod()": FunctionFragment;
    "resolveDisputedClaim(uint256,bytes32,(bytes32,address,uint32,uint32,uint32,uint8,address))": FunctionFragment;
    "sendMessage(bytes32[],uint64,address,bytes)": FunctionFragment;
    "sequencerDelayLimit()": FunctionFragment;
    "sequencerDelayLimitDecreaseRequest()": FunctionFragment;
    "startVerification(uint256,(bytes32,address,uint32,uint32,uint32,uint8,address))": FunctionFragment;
    "stateRoot()": FunctionFragment;
    "timeoutEpochs()": FunctionFragment;
    "updateSequencerDelayLimit()": FunctionFragment;
    "veaInboxArbToEth()": FunctionFragment;
    "verifySnapshot(uint256,(bytes32,address,uint32,uint32,uint32,uint8,address))": FunctionFragment;
    "withdrawChallengeDeposit(uint256,(bytes32,address,uint32,uint32,uint32,uint8,address))": FunctionFragment;
    "withdrawChallengerEscapeHatch(uint256,(bytes32,address,uint32,uint32,uint32,uint8,address))": FunctionFragment;
    "withdrawClaimDeposit(uint256,(bytes32,address,uint32,uint32,uint32,uint8,address))": FunctionFragment;
    "withdrawClaimerEscapeHatch(uint256,(bytes32,address,uint32,uint32,uint32,uint8,address))": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "BURN_ADDRESS"
      | "arbSys"
      | "bridge"
      | "burn"
      | "censorshipTestStatus"
      | "challenge(uint256,(bytes32,address,uint32,uint32,uint32,uint8,address))"
      | "challenge(uint256,(bytes32,address,uint32,uint32,uint32,uint8,address),address)"
      | "claim"
      | "claimHashes"
      | "deposit"
      | "depositPlusReward"
      | "epochAt"
      | "epochNow"
      | "epochPeriod"
      | "executeSequencerDelayLimitDecreaseRequest"
      | "hashClaim"
      | "isMsgRelayed"
      | "latestVerifiedEpoch"
      | "maxMissingBlocks"
      | "minChallengePeriod"
      | "resolveDisputedClaim"
      | "sendMessage"
      | "sequencerDelayLimit"
      | "sequencerDelayLimitDecreaseRequest"
      | "startVerification"
      | "stateRoot"
      | "timeoutEpochs"
      | "updateSequencerDelayLimit"
      | "veaInboxArbToEth"
      | "verifySnapshot"
      | "withdrawChallengeDeposit"
      | "withdrawChallengerEscapeHatch"
      | "withdrawClaimDeposit"
      | "withdrawClaimerEscapeHatch"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "BURN_ADDRESS", values?: undefined): string;
  encodeFunctionData(functionFragment: "arbSys", values?: undefined): string;
  encodeFunctionData(functionFragment: "bridge", values?: undefined): string;
  encodeFunctionData(functionFragment: "burn", values?: undefined): string;
  encodeFunctionData(functionFragment: "censorshipTestStatus", values: [ClaimStruct]): string;
  encodeFunctionData(
    functionFragment: "challenge(uint256,(bytes32,address,uint32,uint32,uint32,uint8,address))",
    values: [PromiseOrValue<BigNumberish>, ClaimStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "challenge(uint256,(bytes32,address,uint32,uint32,uint32,uint8,address),address)",
    values: [PromiseOrValue<BigNumberish>, ClaimStruct, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "claim",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "claimHashes", values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(functionFragment: "depositPlusReward", values?: undefined): string;
  encodeFunctionData(functionFragment: "epochAt", values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(functionFragment: "epochNow", values?: undefined): string;
  encodeFunctionData(functionFragment: "epochPeriod", values?: undefined): string;
  encodeFunctionData(functionFragment: "executeSequencerDelayLimitDecreaseRequest", values?: undefined): string;
  encodeFunctionData(functionFragment: "hashClaim", values: [ClaimStruct]): string;
  encodeFunctionData(functionFragment: "isMsgRelayed", values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(functionFragment: "latestVerifiedEpoch", values?: undefined): string;
  encodeFunctionData(functionFragment: "maxMissingBlocks", values?: undefined): string;
  encodeFunctionData(functionFragment: "minChallengePeriod", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "resolveDisputedClaim",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BytesLike>, ClaimStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "sendMessage",
    values: [
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(functionFragment: "sequencerDelayLimit", values?: undefined): string;
  encodeFunctionData(functionFragment: "sequencerDelayLimitDecreaseRequest", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "startVerification",
    values: [PromiseOrValue<BigNumberish>, ClaimStruct]
  ): string;
  encodeFunctionData(functionFragment: "stateRoot", values?: undefined): string;
  encodeFunctionData(functionFragment: "timeoutEpochs", values?: undefined): string;
  encodeFunctionData(functionFragment: "updateSequencerDelayLimit", values?: undefined): string;
  encodeFunctionData(functionFragment: "veaInboxArbToEth", values?: undefined): string;
  encodeFunctionData(functionFragment: "verifySnapshot", values: [PromiseOrValue<BigNumberish>, ClaimStruct]): string;
  encodeFunctionData(
    functionFragment: "withdrawChallengeDeposit",
    values: [PromiseOrValue<BigNumberish>, ClaimStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawChallengerEscapeHatch",
    values: [PromiseOrValue<BigNumberish>, ClaimStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawClaimDeposit",
    values: [PromiseOrValue<BigNumberish>, ClaimStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawClaimerEscapeHatch",
    values: [PromiseOrValue<BigNumberish>, ClaimStruct]
  ): string;

  decodeFunctionResult(functionFragment: "BURN_ADDRESS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "arbSys", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bridge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "censorshipTestStatus", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "challenge(uint256,(bytes32,address,uint32,uint32,uint32,uint8,address))",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "challenge(uint256,(bytes32,address,uint32,uint32,uint32,uint8,address),address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimHashes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "depositPlusReward", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "epochAt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "epochNow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "epochPeriod", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "executeSequencerDelayLimitDecreaseRequest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hashClaim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isMsgRelayed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "latestVerifiedEpoch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maxMissingBlocks", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "minChallengePeriod", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "resolveDisputedClaim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sendMessage", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sequencerDelayLimit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sequencerDelayLimitDecreaseRequest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "startVerification", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stateRoot", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "timeoutEpochs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "updateSequencerDelayLimit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "veaInboxArbToEth", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifySnapshot", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdrawChallengeDeposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdrawChallengerEscapeHatch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdrawClaimDeposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdrawClaimerEscapeHatch", data: BytesLike): Result;

  events: {
    "Challenged(uint256,address)": EventFragment;
    "Claimed(address,uint256,bytes32)": EventFragment;
    "MessageRelayed(uint64)": EventFragment;
    "VerificationStarted(uint256)": EventFragment;
    "Verified(uint256)": EventFragment;
    "sequencerDelayLimitDecreaseRequested(uint256)": EventFragment;
    "sequencerDelayLimitUpdated(uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Challenged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Claimed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MessageRelayed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VerificationStarted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Verified"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "sequencerDelayLimitDecreaseRequested"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "sequencerDelayLimitUpdated"): EventFragment;
}

export interface ChallengedEventObject {
  _epoch: BigNumber;
  _challenger: string;
}
export type ChallengedEvent = TypedEvent<[BigNumber, string], ChallengedEventObject>;

export type ChallengedEventFilter = TypedEventFilter<ChallengedEvent>;

export interface ClaimedEventObject {
  _claimer: string;
  _epoch: BigNumber;
  _stateRoot: string;
}
export type ClaimedEvent = TypedEvent<[string, BigNumber, string], ClaimedEventObject>;

export type ClaimedEventFilter = TypedEventFilter<ClaimedEvent>;

export interface MessageRelayedEventObject {
  _msgId: BigNumber;
}
export type MessageRelayedEvent = TypedEvent<[BigNumber], MessageRelayedEventObject>;

export type MessageRelayedEventFilter = TypedEventFilter<MessageRelayedEvent>;

export interface VerificationStartedEventObject {
  _epoch: BigNumber;
}
export type VerificationStartedEvent = TypedEvent<[BigNumber], VerificationStartedEventObject>;

export type VerificationStartedEventFilter = TypedEventFilter<VerificationStartedEvent>;

export interface VerifiedEventObject {
  _epoch: BigNumber;
}
export type VerifiedEvent = TypedEvent<[BigNumber], VerifiedEventObject>;

export type VerifiedEventFilter = TypedEventFilter<VerifiedEvent>;

export interface sequencerDelayLimitDecreaseRequestedEventObject {
  _requestedSequencerDelayLimit: BigNumber;
}
export type sequencerDelayLimitDecreaseRequestedEvent = TypedEvent<
  [BigNumber],
  sequencerDelayLimitDecreaseRequestedEventObject
>;

export type sequencerDelayLimitDecreaseRequestedEventFilter =
  TypedEventFilter<sequencerDelayLimitDecreaseRequestedEvent>;

export interface sequencerDelayLimitUpdatedEventObject {
  _newSequencerDelayLimit: BigNumber;
}
export type sequencerDelayLimitUpdatedEvent = TypedEvent<[BigNumber], sequencerDelayLimitUpdatedEventObject>;

export type sequencerDelayLimitUpdatedEventFilter = TypedEventFilter<sequencerDelayLimitUpdatedEvent>;

export interface VeaOutboxMockArbToEth extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: VeaOutboxMockArbToEthInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    BURN_ADDRESS(overrides?: CallOverrides): Promise<[string]>;

    arbSys(overrides?: CallOverrides): Promise<[string]>;

    bridge(overrides?: CallOverrides): Promise<[string]>;

    burn(overrides?: CallOverrides): Promise<[BigNumber]>;

    censorshipTestStatus(_claim: ClaimStruct, overrides?: CallOverrides): Promise<[number] & { status: number }>;

    "challenge(uint256,(bytes32,address,uint32,uint32,uint32,uint8,address))"(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "challenge(uint256,(bytes32,address,uint32,uint32,uint32,uint8,address),address)"(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      _withdrawalAddress: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    claim(
      _epoch: PromiseOrValue<BigNumberish>,
      _stateRoot: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    claimHashes(arg0: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<[string]>;

    deposit(overrides?: CallOverrides): Promise<[BigNumber]>;

    depositPlusReward(overrides?: CallOverrides): Promise<[BigNumber]>;

    epochAt(
      timestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { epoch: BigNumber }>;

    epochNow(overrides?: CallOverrides): Promise<[BigNumber] & { epoch: BigNumber }>;

    epochPeriod(overrides?: CallOverrides): Promise<[BigNumber]>;

    executeSequencerDelayLimitDecreaseRequest(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    hashClaim(_claim: ClaimStruct, overrides?: CallOverrides): Promise<[string] & { hashedClaim: string }>;

    isMsgRelayed(
      _msgId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean] & { isRelayed: boolean }>;

    latestVerifiedEpoch(overrides?: CallOverrides): Promise<[BigNumber]>;

    maxMissingBlocks(overrides?: CallOverrides): Promise<[BigNumber]>;

    minChallengePeriod(overrides?: CallOverrides): Promise<[BigNumber]>;

    resolveDisputedClaim(
      _epoch: PromiseOrValue<BigNumberish>,
      _stateRoot: PromiseOrValue<BytesLike>,
      _claim: ClaimStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sendMessage(
      _proof: PromiseOrValue<BytesLike>[],
      _msgId: PromiseOrValue<BigNumberish>,
      _to: PromiseOrValue<string>,
      _message: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sequencerDelayLimit(overrides?: CallOverrides): Promise<[BigNumber]>;

    sequencerDelayLimitDecreaseRequest(overrides?: CallOverrides): Promise<
      [BigNumber, BigNumber] & {
        requestedsequencerDelayLimit: BigNumber;
        timestamp: BigNumber;
      }
    >;

    startVerification(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    stateRoot(overrides?: CallOverrides): Promise<[string]>;

    timeoutEpochs(overrides?: CallOverrides): Promise<[BigNumber]>;

    updateSequencerDelayLimit(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<ContractTransaction>;

    veaInboxArbToEth(overrides?: CallOverrides): Promise<[string]>;

    verifySnapshot(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawChallengeDeposit(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawChallengerEscapeHatch(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawClaimDeposit(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawClaimerEscapeHatch(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  BURN_ADDRESS(overrides?: CallOverrides): Promise<string>;

  arbSys(overrides?: CallOverrides): Promise<string>;

  bridge(overrides?: CallOverrides): Promise<string>;

  burn(overrides?: CallOverrides): Promise<BigNumber>;

  censorshipTestStatus(_claim: ClaimStruct, overrides?: CallOverrides): Promise<number>;

  "challenge(uint256,(bytes32,address,uint32,uint32,uint32,uint8,address))"(
    _epoch: PromiseOrValue<BigNumberish>,
    _claim: ClaimStruct,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "challenge(uint256,(bytes32,address,uint32,uint32,uint32,uint8,address),address)"(
    _epoch: PromiseOrValue<BigNumberish>,
    _claim: ClaimStruct,
    _withdrawalAddress: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  claim(
    _epoch: PromiseOrValue<BigNumberish>,
    _stateRoot: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  claimHashes(arg0: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<string>;

  deposit(overrides?: CallOverrides): Promise<BigNumber>;

  depositPlusReward(overrides?: CallOverrides): Promise<BigNumber>;

  epochAt(timestamp: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

  epochNow(overrides?: CallOverrides): Promise<BigNumber>;

  epochPeriod(overrides?: CallOverrides): Promise<BigNumber>;

  executeSequencerDelayLimitDecreaseRequest(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  hashClaim(_claim: ClaimStruct, overrides?: CallOverrides): Promise<string>;

  isMsgRelayed(_msgId: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<boolean>;

  latestVerifiedEpoch(overrides?: CallOverrides): Promise<BigNumber>;

  maxMissingBlocks(overrides?: CallOverrides): Promise<BigNumber>;

  minChallengePeriod(overrides?: CallOverrides): Promise<BigNumber>;

  resolveDisputedClaim(
    _epoch: PromiseOrValue<BigNumberish>,
    _stateRoot: PromiseOrValue<BytesLike>,
    _claim: ClaimStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sendMessage(
    _proof: PromiseOrValue<BytesLike>[],
    _msgId: PromiseOrValue<BigNumberish>,
    _to: PromiseOrValue<string>,
    _message: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sequencerDelayLimit(overrides?: CallOverrides): Promise<BigNumber>;

  sequencerDelayLimitDecreaseRequest(overrides?: CallOverrides): Promise<
    [BigNumber, BigNumber] & {
      requestedsequencerDelayLimit: BigNumber;
      timestamp: BigNumber;
    }
  >;

  startVerification(
    _epoch: PromiseOrValue<BigNumberish>,
    _claim: ClaimStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  stateRoot(overrides?: CallOverrides): Promise<string>;

  timeoutEpochs(overrides?: CallOverrides): Promise<BigNumber>;

  updateSequencerDelayLimit(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<ContractTransaction>;

  veaInboxArbToEth(overrides?: CallOverrides): Promise<string>;

  verifySnapshot(
    _epoch: PromiseOrValue<BigNumberish>,
    _claim: ClaimStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawChallengeDeposit(
    _epoch: PromiseOrValue<BigNumberish>,
    _claim: ClaimStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawChallengerEscapeHatch(
    _epoch: PromiseOrValue<BigNumberish>,
    _claim: ClaimStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawClaimDeposit(
    _epoch: PromiseOrValue<BigNumberish>,
    _claim: ClaimStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawClaimerEscapeHatch(
    _epoch: PromiseOrValue<BigNumberish>,
    _claim: ClaimStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    BURN_ADDRESS(overrides?: CallOverrides): Promise<string>;

    arbSys(overrides?: CallOverrides): Promise<string>;

    bridge(overrides?: CallOverrides): Promise<string>;

    burn(overrides?: CallOverrides): Promise<BigNumber>;

    censorshipTestStatus(_claim: ClaimStruct, overrides?: CallOverrides): Promise<number>;

    "challenge(uint256,(bytes32,address,uint32,uint32,uint32,uint8,address))"(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    "challenge(uint256,(bytes32,address,uint32,uint32,uint32,uint8,address),address)"(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      _withdrawalAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    claim(
      _epoch: PromiseOrValue<BigNumberish>,
      _stateRoot: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    claimHashes(arg0: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<string>;

    deposit(overrides?: CallOverrides): Promise<BigNumber>;

    depositPlusReward(overrides?: CallOverrides): Promise<BigNumber>;

    epochAt(timestamp: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    epochNow(overrides?: CallOverrides): Promise<BigNumber>;

    epochPeriod(overrides?: CallOverrides): Promise<BigNumber>;

    executeSequencerDelayLimitDecreaseRequest(overrides?: CallOverrides): Promise<void>;

    hashClaim(_claim: ClaimStruct, overrides?: CallOverrides): Promise<string>;

    isMsgRelayed(_msgId: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<boolean>;

    latestVerifiedEpoch(overrides?: CallOverrides): Promise<BigNumber>;

    maxMissingBlocks(overrides?: CallOverrides): Promise<BigNumber>;

    minChallengePeriod(overrides?: CallOverrides): Promise<BigNumber>;

    resolveDisputedClaim(
      _epoch: PromiseOrValue<BigNumberish>,
      _stateRoot: PromiseOrValue<BytesLike>,
      _claim: ClaimStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    sendMessage(
      _proof: PromiseOrValue<BytesLike>[],
      _msgId: PromiseOrValue<BigNumberish>,
      _to: PromiseOrValue<string>,
      _message: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    sequencerDelayLimit(overrides?: CallOverrides): Promise<BigNumber>;

    sequencerDelayLimitDecreaseRequest(overrides?: CallOverrides): Promise<
      [BigNumber, BigNumber] & {
        requestedsequencerDelayLimit: BigNumber;
        timestamp: BigNumber;
      }
    >;

    startVerification(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    stateRoot(overrides?: CallOverrides): Promise<string>;

    timeoutEpochs(overrides?: CallOverrides): Promise<BigNumber>;

    updateSequencerDelayLimit(overrides?: CallOverrides): Promise<void>;

    veaInboxArbToEth(overrides?: CallOverrides): Promise<string>;

    verifySnapshot(_epoch: PromiseOrValue<BigNumberish>, _claim: ClaimStruct, overrides?: CallOverrides): Promise<void>;

    withdrawChallengeDeposit(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawChallengerEscapeHatch(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawClaimDeposit(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawClaimerEscapeHatch(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Challenged(uint256,address)"(
      _epoch?: PromiseOrValue<BigNumberish> | null,
      _challenger?: PromiseOrValue<string> | null
    ): ChallengedEventFilter;
    Challenged(
      _epoch?: PromiseOrValue<BigNumberish> | null,
      _challenger?: PromiseOrValue<string> | null
    ): ChallengedEventFilter;

    "Claimed(address,uint256,bytes32)"(
      _claimer?: PromiseOrValue<string> | null,
      _epoch?: PromiseOrValue<BigNumberish> | null,
      _stateRoot?: null
    ): ClaimedEventFilter;
    Claimed(
      _claimer?: PromiseOrValue<string> | null,
      _epoch?: PromiseOrValue<BigNumberish> | null,
      _stateRoot?: null
    ): ClaimedEventFilter;

    "MessageRelayed(uint64)"(_msgId?: null): MessageRelayedEventFilter;
    MessageRelayed(_msgId?: null): MessageRelayedEventFilter;

    "VerificationStarted(uint256)"(_epoch?: PromiseOrValue<BigNumberish> | null): VerificationStartedEventFilter;
    VerificationStarted(_epoch?: PromiseOrValue<BigNumberish> | null): VerificationStartedEventFilter;

    "Verified(uint256)"(_epoch?: null): VerifiedEventFilter;
    Verified(_epoch?: null): VerifiedEventFilter;

    "sequencerDelayLimitDecreaseRequested(uint256)"(
      _requestedSequencerDelayLimit?: null
    ): sequencerDelayLimitDecreaseRequestedEventFilter;
    sequencerDelayLimitDecreaseRequested(
      _requestedSequencerDelayLimit?: null
    ): sequencerDelayLimitDecreaseRequestedEventFilter;

    "sequencerDelayLimitUpdated(uint256)"(_newSequencerDelayLimit?: null): sequencerDelayLimitUpdatedEventFilter;
    sequencerDelayLimitUpdated(_newSequencerDelayLimit?: null): sequencerDelayLimitUpdatedEventFilter;
  };

  estimateGas: {
    BURN_ADDRESS(overrides?: CallOverrides): Promise<BigNumber>;

    arbSys(overrides?: CallOverrides): Promise<BigNumber>;

    bridge(overrides?: CallOverrides): Promise<BigNumber>;

    burn(overrides?: CallOverrides): Promise<BigNumber>;

    censorshipTestStatus(_claim: ClaimStruct, overrides?: CallOverrides): Promise<BigNumber>;

    "challenge(uint256,(bytes32,address,uint32,uint32,uint32,uint8,address))"(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "challenge(uint256,(bytes32,address,uint32,uint32,uint32,uint8,address),address)"(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      _withdrawalAddress: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    claim(
      _epoch: PromiseOrValue<BigNumberish>,
      _stateRoot: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    claimHashes(arg0: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    deposit(overrides?: CallOverrides): Promise<BigNumber>;

    depositPlusReward(overrides?: CallOverrides): Promise<BigNumber>;

    epochAt(timestamp: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    epochNow(overrides?: CallOverrides): Promise<BigNumber>;

    epochPeriod(overrides?: CallOverrides): Promise<BigNumber>;

    executeSequencerDelayLimitDecreaseRequest(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    hashClaim(_claim: ClaimStruct, overrides?: CallOverrides): Promise<BigNumber>;

    isMsgRelayed(_msgId: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    latestVerifiedEpoch(overrides?: CallOverrides): Promise<BigNumber>;

    maxMissingBlocks(overrides?: CallOverrides): Promise<BigNumber>;

    minChallengePeriod(overrides?: CallOverrides): Promise<BigNumber>;

    resolveDisputedClaim(
      _epoch: PromiseOrValue<BigNumberish>,
      _stateRoot: PromiseOrValue<BytesLike>,
      _claim: ClaimStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sendMessage(
      _proof: PromiseOrValue<BytesLike>[],
      _msgId: PromiseOrValue<BigNumberish>,
      _to: PromiseOrValue<string>,
      _message: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sequencerDelayLimit(overrides?: CallOverrides): Promise<BigNumber>;

    sequencerDelayLimitDecreaseRequest(overrides?: CallOverrides): Promise<BigNumber>;

    startVerification(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    stateRoot(overrides?: CallOverrides): Promise<BigNumber>;

    timeoutEpochs(overrides?: CallOverrides): Promise<BigNumber>;

    updateSequencerDelayLimit(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<BigNumber>;

    veaInboxArbToEth(overrides?: CallOverrides): Promise<BigNumber>;

    verifySnapshot(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawChallengeDeposit(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawChallengerEscapeHatch(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawClaimDeposit(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawClaimerEscapeHatch(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    BURN_ADDRESS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    arbSys(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    bridge(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    burn(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    censorshipTestStatus(_claim: ClaimStruct, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "challenge(uint256,(bytes32,address,uint32,uint32,uint32,uint8,address))"(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "challenge(uint256,(bytes32,address,uint32,uint32,uint32,uint8,address),address)"(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      _withdrawalAddress: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    claim(
      _epoch: PromiseOrValue<BigNumberish>,
      _stateRoot: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    claimHashes(arg0: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deposit(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    depositPlusReward(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    epochAt(timestamp: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    epochNow(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    epochPeriod(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    executeSequencerDelayLimitDecreaseRequest(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    hashClaim(_claim: ClaimStruct, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isMsgRelayed(_msgId: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    latestVerifiedEpoch(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maxMissingBlocks(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    minChallengePeriod(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    resolveDisputedClaim(
      _epoch: PromiseOrValue<BigNumberish>,
      _stateRoot: PromiseOrValue<BytesLike>,
      _claim: ClaimStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sendMessage(
      _proof: PromiseOrValue<BytesLike>[],
      _msgId: PromiseOrValue<BigNumberish>,
      _to: PromiseOrValue<string>,
      _message: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sequencerDelayLimit(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sequencerDelayLimitDecreaseRequest(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    startVerification(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    stateRoot(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    timeoutEpochs(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    updateSequencerDelayLimit(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<PopulatedTransaction>;

    veaInboxArbToEth(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    verifySnapshot(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawChallengeDeposit(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawChallengerEscapeHatch(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawClaimDeposit(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawClaimerEscapeHatch(
      _epoch: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
