# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: relayer-envio-inbox
contracts:
  - name: VeaInboxArbToEth
    handler: src/EventHandlers.ts
    events:
      - event: MessageSent(bytes _nodeData)
      - event: SnapshotSaved(bytes32 _snapshot, uint256 _epoch, uint64 _count)
      - event: SnapshotSent(uint256 indexed _epochSent, bytes32 _ticketId)
chains:
  - id: 421614
    start_block: 189388217
    contracts:
      - name: VeaInboxArbToEth
        address:
          - 0x8B925669606026CcCfAFD72840F5b0CAeDA80078
          - 0x45138BC4E364A16919C4571699171d774A7590BD
