/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISequencerFutureUpdatable,
  ISequencerFutureUpdatableInterface,
} from "../../../interfaces/updaters/ISequencerFutureUpdatable";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_newSequencerFutureLimit",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_timestamp",
        type: "uint256",
      },
    ],
    name: "updateSequencerFutureLimit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISequencerFutureUpdatable__factory {
  static readonly abi = _abi;
  static createInterface(): ISequencerFutureUpdatableInterface {
    return new utils.Interface(_abi) as ISequencerFutureUpdatableInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ISequencerFutureUpdatable {
    return new Contract(address, _abi, signerOrProvider) as ISequencerFutureUpdatable;
  }
}
