/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRouterToArb } from "./IRouterToArb";
export type { IRouterToGnosis } from "./IRouterToGnosis";
