/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from "../../common";

export type ClaimStruct = {
  stateRoot: PromiseOrValue<BytesLike>;
  claimer: PromiseOrValue<string>;
  timestampClaimed: PromiseOrValue<BigNumberish>;
  timestampVerification: PromiseOrValue<BigNumberish>;
  blocknumberVerification: PromiseOrValue<BigNumberish>;
  honest: PromiseOrValue<BigNumberish>;
  challenger: PromiseOrValue<string>;
};

export type ClaimStructOutput = [string, string, number, number, number, number, string] & {
  stateRoot: string;
  claimer: string;
  timestampClaimed: number;
  timestampVerification: number;
  blocknumberVerification: number;
  honest: number;
  challenger: string;
};

export interface IRouterToGnosisInterface extends utils.Interface {
  functions: {
    "route(uint256,bytes32,uint256,(bytes32,address,uint32,uint32,uint32,uint8,address))": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "route"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "route",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>, ClaimStruct]
  ): string;

  decodeFunctionResult(functionFragment: "route", data: BytesLike): Result;

  events: {};
}

export interface IRouterToGnosis extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IRouterToGnosisInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    route(
      _epoch: PromiseOrValue<BigNumberish>,
      _stateRoot: PromiseOrValue<BytesLike>,
      _gasLimit: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  route(
    _epoch: PromiseOrValue<BigNumberish>,
    _stateRoot: PromiseOrValue<BytesLike>,
    _gasLimit: PromiseOrValue<BigNumberish>,
    _claim: ClaimStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    route(
      _epoch: PromiseOrValue<BigNumberish>,
      _stateRoot: PromiseOrValue<BytesLike>,
      _gasLimit: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    route(
      _epoch: PromiseOrValue<BigNumberish>,
      _stateRoot: PromiseOrValue<BytesLike>,
      _gasLimit: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    route(
      _epoch: PromiseOrValue<BigNumberish>,
      _stateRoot: PromiseOrValue<BytesLike>,
      _gasLimit: PromiseOrValue<BigNumberish>,
      _claim: ClaimStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
