/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from "../../common";

export interface IRouterToArbInterface extends utils.Interface {
  functions: {
    "route(uint256,bytes32,uint256,uint256,address,uint256,uint256)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "route"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "route",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "route", data: BytesLike): Result;

  events: {};
}

export interface IRouterToArb extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IRouterToArbInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    route(
      _epoch: PromiseOrValue<BigNumberish>,
      _stateroot: PromiseOrValue<BytesLike>,
      _inboxIndex: PromiseOrValue<BigNumberish>,
      _maxSubmissionCost: PromiseOrValue<BigNumberish>,
      _excessFeeRefundAddress: PromiseOrValue<string>,
      _gasLimit: PromiseOrValue<BigNumberish>,
      _maxFeePerGas: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  route(
    _epoch: PromiseOrValue<BigNumberish>,
    _stateroot: PromiseOrValue<BytesLike>,
    _inboxIndex: PromiseOrValue<BigNumberish>,
    _maxSubmissionCost: PromiseOrValue<BigNumberish>,
    _excessFeeRefundAddress: PromiseOrValue<string>,
    _gasLimit: PromiseOrValue<BigNumberish>,
    _maxFeePerGas: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    route(
      _epoch: PromiseOrValue<BigNumberish>,
      _stateroot: PromiseOrValue<BytesLike>,
      _inboxIndex: PromiseOrValue<BigNumberish>,
      _maxSubmissionCost: PromiseOrValue<BigNumberish>,
      _excessFeeRefundAddress: PromiseOrValue<string>,
      _gasLimit: PromiseOrValue<BigNumberish>,
      _maxFeePerGas: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    route(
      _epoch: PromiseOrValue<BigNumberish>,
      _stateroot: PromiseOrValue<BytesLike>,
      _inboxIndex: PromiseOrValue<BigNumberish>,
      _maxSubmissionCost: PromiseOrValue<BigNumberish>,
      _excessFeeRefundAddress: PromiseOrValue<string>,
      _gasLimit: PromiseOrValue<BigNumberish>,
      _maxFeePerGas: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    route(
      _epoch: PromiseOrValue<BigNumberish>,
      _stateroot: PromiseOrValue<BytesLike>,
      _inboxIndex: PromiseOrValue<BigNumberish>,
      _maxSubmissionCost: PromiseOrValue<BigNumberish>,
      _excessFeeRefundAddress: PromiseOrValue<string>,
      _gasLimit: PromiseOrValue<BigNumberish>,
      _maxFeePerGas: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
