/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { ISenderGateway, ISenderGatewayInterface } from "../../../interfaces/gateways/ISenderGateway";

const _abi = [
  {
    inputs: [],
    name: "receiverGateway",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "veaInbox",
    outputs: [
      {
        internalType: "contract IVeaInbox",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ISenderGateway__factory {
  static readonly abi = _abi;
  static createInterface(): ISenderGatewayInterface {
    return new utils.Interface(_abi) as ISenderGatewayInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ISenderGateway {
    return new Contract(address, _abi, signerOrProvider) as ISenderGateway;
  }
}
