/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { VeaInboxMockArbToEth__factory } from "./VeaInboxMockArbToEth__factory";
export { VeaOutboxMockArbToEth__factory } from "./VeaOutboxMockArbToEth__factory";
